name: Elixir CI

on: [push]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0.1
          elixir-version: 1.16.x
          experimental-otp: true

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

  test:
    name: Test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 26.x
            elixir: 1.16.x
          - otp: 26.x
            elixir: 1.15.x
          - otp: 26.x
            elixir: 1.14.5
          - otp: 25.x
            elixir: 1.13.4
          - otp: 24.x
            elixir: 1.12.3
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          experimental-otp: true

      - name: Install dependencies
        run: mix deps.get

      - name: Start docker
        run: docker-compose up --detach

      - name: Run tests
        run: mix test --trace
